application: podcast-test-7234567813457
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: bg_search.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

